name: meditouch
description: "MediTouch is a groundbreaking initiative aimed at transforming healthcare delivery by providing comprehensive healthcare services to remote and underserved areas through a simple, user-friendly app. The system is to reach the rural areas of our country and solve pressing medical issues."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  video_player: ^2.9.2
  r_icon_pro: ^1.0.3
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  quickalert: ^1.1.0
  blur: ^4.0.0
  salomon_bottom_bar: ^3.3.2
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.8.0
  flutter_animate: ^4.5.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.4
  infinite_scroll_pagination: ^4.1.0
  flutter_html: ^3.0.0-beta.2
  loading_animation_widget: ^1.3.0
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
          weight: 600
  